### PR TITLE
Fix two small backend issues - add new user on auth, return 400 on invalid id parameter

### LINKED ISSUE #75: Add new user to db when new user logs in

### LINKED ISSUE #92: Add check of validity to id parameters in each relevant servlet

### PR DESCRIPTION
**Pull request by roonil-wazlib**
- authentication now creates new user in database when given unfamiliar login details
 - all relevant servlets now return a 400 bad request error when supplied with not integer ids for users or competitions

Resolves #92, Resolves #75

### CODE REVIEW

**Review by lin8231 — APPROVED** [review]
LGTM

**Review by Phoebe-Khokgawe — APPROVED** [review]
LGTM

File: project/src/main/java/com/google/sps/servlets/AuthServlet.java [hunk 1]
```diff
@@ -73,4 +81,24 @@ private User getUser(Connection conn, String email) throws SQLException {
...
+  private User addUser(Connection conn, String name, String email) throws SQLException {
+    String stmt = "INSERT INTO users (name, email) VALUES ('" + name + "', '" + email + "');";
+    try (PreparedStatement userStmt = conn.prepareStatement(stmt);) {
+      // Execute the statement
+      userStmt.execute();
+      LOGGER.log(Level.INFO, "User " + name + " added to database.");
+
+    }
+    String getId = "SELECT LAST_INSERT_ID();";
+    try (PreparedStatement idStmt = conn.prepareStatement(getId);) {
```
Comment (leonnemets) [inline project/src/main/java/com/google/sps/servlets/AuthServlet.java:94]: when Sgonks becomes very popular, this may cause an issue when 2 new users sign up "instantaneously" could last_insert_id be wrong?

**Review by leonnemets — APPROVED** [review]
LGTM. please address the comment. Thanks for handling the bad request

File: project/src/main/java/com/google/sps/servlets/AuthServlet.java (hunk 1 above)
Comment (texm) [reply project/src/main/java/com/google/sps/servlets/AuthServlet.java:94]: https://docs.oracle.com/javadb/10.8.3.0/ref/crefjavstateautogen.html may be of use

Comment (roonil-wazlib) [reply project/src/main/java/com/google/sps/servlets/AuthServlet.java:94]: @leonnemets https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_last-insert-id LAST_INSERT_ID operates on a per connection basis so I don't think should be an issue?
